version: '3'

services:
  swoole:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
    - "./app:/var/www"
    ports:
      - 8099:9501

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/fpm
      dockerfile: Dockerfile
    volumes:
      - ./app:/app

  express:
    image: node:12.14.1-alpine
    working_dir: /app
    container_name: node
    volumes:
      - ./server.js:/app/server.js
      - ./node_modules:/app/node_modules
    command: node server.js
    ports:
      - "3000:3000"