version: '3'

services:
  swoole:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
    - "./app/socket:/var/www"
    ports:
      - "8099:9502"

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - php-fpm
      - swoole

  php-fpm:
    build:
      context: docker/fpm
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
